### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by xitrumcute** [BestGamersH/Multipurpose-Discord-Bot#3]
Error: The module '\\?\D:\Multipurpose-Discord-Bot-main\Multipurpose-Discord-Bot-main\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Multipurpose-Discord-Bot-main\Multipurpose-Discord-Bot-main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\Multipurpose-Discord-Bot-main\Multipurpose-Discord-Bot-main\node_modules\canvas\lib\canvas.js:9:18) 
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)

how to fix?

**Comment by BestGamersH** [comment]
Reinstall node.js

**Comment by AwesomePerson2** [comment]
what version of nodejs are you using
