### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Drew-The-Gangster-Cowboy** [BestGamersH/Multipurpose-Discord-Bot#44]
UNHANDLED REJECTION
Reason: TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/runner/Multipurpose-Discord-Bot/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/runner/Multipurpose-Discord-Bot/node_modules/cron/lib/cron.js:600:23) at Timeout.callbackWrapper [as onTimeout] (/home/runner/Multipurpose-Discord-Bot/node_modules/cron/lib/cron.js:6
67:10)
at listOnTimeout (node: internal/timers:573:17)
at process.processTimers (node: internal/timers:514:7)
UNHANDLED REJECTION

It just repeats this it also will sometimes say 
At check_voice_channels

**Comment by PLoliwi** [comment]
> UNHANDLED REJECTION Reason: TypeError: Cannot read properties of undefined (reading 'get') at CronJob. (/home/runner/Multipurpose-Discord-Bot/handlers/mute.js:64:33) at CronJob.fireOnTick (/home/runner/Multipurpose-Discord-Bot/node_modules/cron/lib/cron.js:600:23) at Timeout.callbackWrapper [as onTimeout] (/home/runner/Multipurpose-Discord-Bot/node_modules/cron/lib/cron.js:6 67:10) at listOnTimeout (node: internal/timers:573:17) at process.processTimers (node: internal/timers:514:7) UNHANDLED REJECTION
> 
> It just repeats this it also will sometimes say At check_voice_channels

Shell

**Comment by PLoliwi** [comment]
npm i -D node@16.6.1

**Comment by BestGamersH** [comment]
Download updated version

**Comment by hotsu0p** [comment]
I also wouldnt reccomennd hosting on replit @Drew-The-Gangster-Cowboy
