### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kippasaurr** [BestGamersH/Multipurpose-Discord-Bot#6]
added 1 package, and audited 530 packages in 6s
62 packages are looking for funding
run `npm fund` for details
16 vulnerabilities (12 moderate, 4 high)
To address issues that do not require attention, run:
npm audit fix
To address all issues possible (including breaking changes), run:
npm audit fix --force
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
Welcome to SERVICE HANDLER /--/ By   /--/ Discord: BestGamersHK#9999
[x] :: Now loading the Commands ...
Error: ENOTDIR: not a directory, scandir './commands/advertisement.json/'
at readdirSync (node:fs:1452:3)
at /home/container/handlers/command.js:14:24
at Array.forEach (<anonymous>)
at module.exports (/home/container/handlers/command.js:13:32)
at /home/container/index.js:123:43
at Array.forEach (<anonymous>)
at requirehandlers (/home/container/index.js:122:102)
at Object.<anonymous> (/home/container/index.js:141:3)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Error: /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at bindings (/home/container/node_modules/bindings/bindings.js:112:48)
at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
at new Enmap (/home/container/node_modules/enmap/src/index.js:152:18)
at module.exports (/home/container/handlers/command.js:35:21)
at /home/container/index.js:123:43
[x] :: Now loading the Database...
Error: /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at bindings (/home/container/node_modules/bindings/bindings.js:112:48)
at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
at new Enmap (/home/container/node_modules/enmap/src/index.js:152:18)
at module.exports (/home/container/handlers/loaddb.js:6:20)
at /home/container/index.js:123:43
[x] :: Now loading the Events ...
[x] :: LOADED THE 15 EVENTS after: 3ms
     ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
     ┃                                                                  ┃
     ┃ Logging into the BOT...                                          ┃
     ┃                                                                  ┃
     ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Error: /home/container/node_modules/canvas/build/Release/canvas.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/canvas.js:9:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/index.js:1:16)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Error: /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at bindings (/home/container/node_modules/bindings/bindings.js:112:48)
at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
at new Enmap (/home/container/node_modules/enmap/src/index.js:152:18)
at module.exports (/home/container/handlers/anti_nuke.js:11:31)
at /home/container/index.js:139:45
at Array.forEach (<anonymous>)
at requirehandlers (/home/container/index.js:138:46)
at Object.<anonymous> (/home/container/index.js:141:3)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:23:47
Error: /home/container/node_modules/canvas/build/Release/canvas.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/canvas.js:9:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/index.js:1:16)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Error: /home/container/node_modules/canvas/build/Release/canvas.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/canvas.js:9:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/index.js:1:16)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Error: /home/container/node_modules/canvas/build/Release/canvas.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/canvas.js:9:18)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/home/container/node_modules/canvas/index.js:1:16)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Provided token: token
Preparing to connect to the gateway...

=== UNHANDLED REJECTION ===
Reason:  Error: /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at bindings (/home/container/node_modules/bindings/bindings.js:112:48)
at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
at new Enmap (/home/container/node_modules/enmap/src/index.js:152:18)
at module.exports (/home/container/handlers/epicgamesverification.js:10:26)
at /home/container/index.js:139:45
at Array.forEach (<anonymous>)
at requirehandlers (/home/container/index.js:138:46)
at Object.<anonymous> (/home/container/index.js:141:3)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:23:47
=== UNHANDLED REJECTION ===

[WS => Manager] Manager was destroyed. Called by:
Error [MANAGER_DESTROYED]: Manager was destroyed.
at WebSocketManager.destroy (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:317:54)
at Client.destroy (/home/container/node_modules/discord.js/src/client/Client.js:284:13)
at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:257:12)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

=== UNHANDLED REJECTION ===
Reason:  Error [TOKEN_INVALID]: An invalid token was provided.
at WebSocketManager.connect (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:129:26)
at Client.login (/home/container/node_modules/discord.js/src/client/Client.js:254:21)
at Object.<anonymous> (/home/container/index.js:147:8)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:23:47
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNCAUGHT EXCEPTION MONITOR ===

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
at CronJob.<anonymous> (/home/container/handlers/autonsfw.js:13:38)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNCAUGHT EXCEPTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNCAUGHT EXCEPTION MONITOR ===

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
at CronJob.<anonymous> (/home/container/handlers/timedmessages.js:13:38)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNCAUGHT EXCEPTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNCAUGHT EXCEPTION MONITOR ===

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
at CronJob.<anonymous> (/home/container/handlers/automeme.js:28:38)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNCAUGHT EXCEPTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNCAUGHT EXCEPTION MONITOR ===

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
at CronJob.<anonymous> (/home/container/handlers/autonsfw.js:13:38)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNCAUGHT EXCEPTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNCAUGHT EXCEPTION MONITOR ===

=== UNCAUGHT EXCEPTION ===
Exception:  TypeError: Cannot read properties of undefined (reading 'filter')
at CronJob.<anonymous> (/home/container/handlers/timedmessages.js:13:38)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNCAUGHT EXCEPTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'ensure')
at CronJob.<anonymous> (/home/container/handlers/mute.js:25:22)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

=== UNHANDLED REJECTION ===
Reason:  TypeError: Cannot read properties of undefined (reading 'get')
at CronJob.<anonymous> (/home/container/handlers/mute.js:64:33)
at CronJob.fireOnTick (/home/container/node_modules/cron/lib/cron.js:600:23)
at Timeout.callbackWrapper [as _onTimeout] (/home/container/node_modules/cron/lib/cron.js:667:10)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
=== UNHANDLED REJECTION ===

**Comment by BestGamersH** [comment]
Use the updated version of it.

**Comment by tro1fake** [comment]
Using the newest version doesnt work

**Comment by NuketheYmap7** [comment]
what version should i use?

**Comment by tro1fake** [comment]
btw the bot is totally fucked cuz 30% of the features doesnt even work

**Comment by PHV08** [comment]
i fixed almost all the errors

**Comment by BestGamersH** [comment]
Join Discord
https://discord.gg/hsmU2c7mVa
